=== IdoiaZabalo/pbl_grupo_4/Pagina Web2/Tabla/Tabla.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="patients">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="patient" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="hospital" type="xs:string" minOccurs="1" maxOccurs="1"/>
			  <xs:element name="order_id" minOccurs="1" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:pattern value="[0-9][0-9][0-9]"/>
					</xs:restriction>
				</xs:simpleType>
			  </xs:element>
              <xs:element name="age" minOccurs="1" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="120"/>
					</xs:restriction>
				</xs:simpleType>
			  </xs:element>
              <xs:element name="diagnosis_date" type="xs:date" minOccurs="1" maxOccurs="1"/>			  
			  <xs:element name="diagnosis" minOccurs="1" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="Glaucoma|No Glaucoma"/>
					</xs:restriction>
				</xs:simpleType>
			  </xs:element>
              <xs:element name="image" type="xs:string" minOccurs="1" maxOccurs="1"/>
              <xs:element name="note" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
			<xs:attribute name="id"  use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[A-Z][0-9]{4}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
          </xs:complexType>		  
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== IdoiaZabalo/pbl_grupo_4/Pagina Web2/Tabla/tabla.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Tabla.xslt"?> 
<!-- <!DOCTYPE patients SYSTEM "Tabla.dtd" []> -->
<patients xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Tabla.xsd">
    <patient id ="C8234">
        <hospital>Cruces</hospital>
        <order_id>201</order_id>
        <age>89</age>
        <diagnosis_date>2024-05-01</diagnosis_date>
        <diagnosis>Glaucoma</diagnosis>
        <image>imagenes/imagen1.jpg</image>
		<note>Glaucoma de ángulo abierto</note>
    </patient>
    <patient id="D1248">
        <hospital>Donostia</hospital>
        <order_id>393</order_id>
        <age>55</age>
        <diagnosis_date>2024-05-02</diagnosis_date>
        <diagnosis>No Glaucoma</diagnosis>
        <image>imagenes/imagen2.jpg</image>
        
    </patient>
	<patient id="D6853">
        <hospital>Donostia</hospital>
        <order_id>200</order_id>
        <age>60</age>
        <diagnosis_date>2024-04-24</diagnosis_date>
        <diagnosis>No Glaucoma</diagnosis>
        <image>imagenes/imagen3.jpg</image>
        
    </patient>
	<patient id="C2344">
        <hospital>Cruces</hospital>
        <order_id>543</order_id>
        <age>73</age>
        <diagnosis_date>2024-05-10</diagnosis_date>
        <diagnosis>Glaucoma</diagnosis>
        <image>imagenes/imagen4.jpg</image>
        <note>Glaucoma de ángulo cerrado</note>
    </patient>
		<patient id="C4906">
        <hospital>Cruces</hospital>
        <order_id>225</order_id>
        <age>58</age>
        <diagnosis_date>2023-12-30</diagnosis_date>
        <diagnosis>Glaucoma</diagnosis>
        <image>imagenes/imagen5.jpg</image>
        <note>Glaucoma de ángulo cerrado</note>
    </patient>
</patients>
