=== IdoiaZabalo/pbl_grupo_4/docs/Tabla/Tabla.dtd
<!ELEMENT patients (patient+)>
<!ELEMENT patient (genero, hospital, order_id, age, diagnosis_date, diagnosis, image, resultados, tratamiento?, dosis?, note?)>
<!ATTLIST patient id CDATA #REQUIRED>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT hospital (#PCDATA)>
<!ELEMENT order_id (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT diagnosis_date (#PCDATA)>
<!ELEMENT diagnosis (#PCDATA)>
<!ELEMENT image (#PCDATA)>
<!ELEMENT resultados (copa, disco, ratio)>
<!ELEMENT copa (#PCDATA)>
<!ELEMENT disco (#PCDATA)>
<!ELEMENT ratio (#PCDATA)>
<!ELEMENT tratamiento (#PCDATA)>
<!ELEMENT dosis (#PCDATA)>
<!ELEMENT note (#PCDATA)>

=== IdoiaZabalo/pbl_grupo_4/docs/Tabla/tabla.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Tabla.xslt"?> 
<!-- <!DOCTYPE patients SYSTEM "Tabla.dtd" []> -->
<patients xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Tabla.xsd">
    <patient id ="C8234">
		<genero>Hombre</genero>
        <hospital>Cruces</hospital>
        <order_id>201</order_id>
        <age>89</age>
        <diagnosis_date>2024-05-01</diagnosis_date>
        <diagnosis>Glaucoma</diagnosis>
        <image>imagenes/imagen1.jpg</image>
		<resultados>
			<copa>Diámetro Copa Ocular: 0.6 mm</copa> 
			<disco>Diámetro Disco Ocular: 1.5 mm</disco> 
			<ratio>Ratio: 0.4</ratio>
		</resultados>
		<tratamiento>Latanoprost</tratamiento>
		<dosis>1 gota en cada ojo una vez al día</dosis>
		<note>Glaucoma de ángulo abierto</note>
    </patient>
    <patient id="D1248">
		<genero>Hombre</genero>
        <hospital>Donostia</hospital>
        <order_id>393</order_id>
        <age>55</age>
        <diagnosis_date>2024-05-02</diagnosis_date>
        <diagnosis>No Glaucoma</diagnosis>
        <image>imagenes/imagen2.jpg</image>
		<resultados>
			<copa>Diámetro Copa Ocular: 0.6 mm</copa> 
			<disco>Diámetro Disco Ocular: 1.5 mm</disco> 
			<ratio>Ratio: 0.4</ratio>
		</resultados>  		
    </patient>
	<patient id="D6853">
		<genero>Mujer</genero>
        <hospital>Donostia</hospital>
        <order_id>200</order_id>
        <age>60</age>
        <diagnosis_date>2024-04-24</diagnosis_date>
        <diagnosis>No Glaucoma</diagnosis>
        <image>imagenes/imagen3.jpg</image>
		<resultados>
			<copa>Diámetro Copa Ocular: 0.6 mm</copa> 
			<disco>Diámetro Disco Ocular: 1.5 mm</disco> 
			<ratio>Ratio: 0.4</ratio>
		</resultados>
    </patient>
	<patient id="C2344">
		<genero>Mujer</genero>
        <hospital>Cruces</hospital>
        <order_id>543</order_id>
        <age>73</age>
        <diagnosis_date>2024-05-10</diagnosis_date>
        <diagnosis>Glaucoma</diagnosis>
        <image>imagenes/imagen4.jpg</image>
		<resultados>
			<copa>Diámetro Copa Ocular: 0.6 mm</copa> 
			<disco>Diámetro Disco Ocular: 1.5 mm</disco> 
			<ratio>Ratio: 0.4</ratio>
		</resultados> 
		<tratamiento>Latanoprost</tratamiento>
		<dosis>1 gota en cada ojo una vez al día</dosis>		
        <note>Glaucoma de ángulo cerrado</note>
    </patient>
	<patient id="C4906">
		<genero>Hombre</genero>
        <hospital>Cruces</hospital>
        <order_id>225</order_id>
        <age>58</age>
        <diagnosis_date>2023-12-30</diagnosis_date>
        <diagnosis>Glaucoma</diagnosis>
        <image>imagenes/imagen5.jpg</image>
		<resultados>
			<copa>Diámetro Copa Ocular: 0.6 mm</copa> 
			<disco>Diámetro Disco Ocular: 1.5 mm</disco> 
			<ratio>Ratio: 0.4</ratio>
		</resultados> 
		<tratamiento>Latanoprost</tratamiento>
		<dosis>1 gota en cada ojo una vez al día</dosis>		
        <note>Glaucoma de ángulo cerrado</note>
    </patient>
</patients>
